### ISSUE TITLE
html tags

### ISSUE THREAD

**Issue by ghost** [impress/impress-extras#1]
how can i use html formatation f.e. the br - Tag with this impress-extra?

**Comment by henrikingo** [comment]
Hi srhuels

This impress-extras repository won't make any sense by itself. You should look at https://github.com/impress/impress.js where it will be included as a git submodule.

**Comment by ghost** [comment]
Hi,i usw impressum.js and tried to Work with the Extension. Searching a way to Put in some Linebreaks....RegardsSvenSent from Android MobilphoneAm 29.07.2018 15:06 schrieb Henrik Ingo <notifications@github.com>:Hi srhuels
This impress-extras repository won't make any sense by itself. You should look at https://github.com/impress/impress.js where it will be included as a git submodule.
